In [1]:
import pandas as pd

# Example DataFrame for illustration
data = {
    "relationship": ["Husband", "Wife", "Own-child", "Not-in-family", "Other-relative", "Husband"],
    "hours-per-week": [40, 30, 20, 45, 35, 50],
}

df = pd.DataFrame(data)

# Step 1: Determine `n` from the SID
SID = 2294984  
n = SID % 10
if n == 0:
    n = 10

print("Step 1: Determined n =", n)

# Step 2: Reduce "hours-per-week" by subtracting `n`
def reduce_hours(hours):
    return hours - n

df["reduced_hours-per-week"] = df["hours-per-week"].apply(reduce_hours)
print("\nStep 2: DataFrame after reducing 'hours-per-week'")
print(df)

# Step 3: Group by "relationship" and original/reduced "hours-per-week"
grouped_original = df.groupby(["relationship", "hours-per-week"]).size().reset_index(name="count")
grouped_reduced = df.groupby(["relationship", "reduced_hours-per-week"]).size().reset_index(name="count")

print("\nStep 3: Grouped by 'relationship' and original 'hours-per-week'")
print(grouped_original)

print("\nGrouped by 'relationship' and reduced 'hours-per-week'")
print(grouped_reduced)

# Lab Logbook Summary
print("\nLab Logbook Summary:")
print("Original DataFrame:")
print(df[["relationship", "hours-per-week"]])

print("\nReduced 'hours-per-week' DataFrame:")
print(df)

print("\nGrouped by original 'hours-per-week':")
print(grouped_original)

print("\nGrouped by reduced 'hours-per-week':")
print(grouped_reduced)

Step 1: Determined n = 4

Step 2: DataFrame after reducing 'hours-per-week'
     relationship  hours-per-week  reduced_hours-per-week
0         Husband              40                      36
1            Wife              30                      26
2       Own-child              20                      16
3   Not-in-family              45                      41
4  Other-relative              35                      31
5         Husband              50                      46

Step 3: Grouped by 'relationship' and original 'hours-per-week'
     relationship  hours-per-week  count
0         Husband              40      1
1         Husband              50      1
2   Not-in-family              45      1
3  Other-relative              35      1
4       Own-child              20      1
5            Wife              30      1

Grouped by 'relationship' and reduced 'hours-per-week'
     relationship  reduced_hours-per-week  count
0         Husband                      36      1
1         Husband                      46      1
2   Not-in-family                      41      1
3  Other-relative                      31      1
4       Own-child                      16      1
5            Wife                      26      1

Lab Logbook Summary:
Original DataFrame:
     relationship  hours-per-week
0         Husband              40
1            Wife              30
2       Own-child              20
3   Not-in-family              45
4  Other-relative              35
5         Husband              50

Reduced 'hours-per-week' DataFrame:
     relationship  hours-per-week  reduced_hours-per-week
0         Husband              40                      36
1            Wife              30                      26
2       Own-child              20                      16
3   Not-in-family              45                      41
4  Other-relative              35                      31
5         Husband              50                      46

Grouped by original 'hours-per-week':
     relationship  hours-per-week  count
0         Husband              40      1
1         Husband              50      1
2   Not-in-family              45      1
3  Other-relative              35      1
4       Own-child              20      1
5            Wife              30      1

Grouped by reduced 'hours-per-week':
     relationship  reduced_hours-per-week  count
0         Husband                      36      1
1         Husband                      46      1
2   Not-in-family                      41      1
3  Other-relative                      31      1
4       Own-child                      16      1
5            Wife                      26      1